### ISSUE TITLE
twilio verifiation code bug / phone number 

### ISSUE THREAD

**Issue by hichemsmairia** [JackZheng10/Laundr-Web-App#1]
hi , i cloned the project and i set up the db uri and the twilio setting ... when i try to create an account it always shows me that the code is wrong .. am in tunisia so ouw phone number looks like +216 xx xxx xxx ... 8 digits not 10 .. i dunno how to fix it

**Comment by JackZheng10** [comment]
Hey Hichem, thanks for your interest with this. 

I would verify that what you're typing is indeed the code that it's being checked against. In Register.js, lines 355 and 356 console log these 2 fields before submission. So open up your browser console and check that. Other than that, this might be an error that I need to handle (I still have a decent bit of testing/fixing for the register section).

**Comment by hichemsmairia** [comment]
i bypassed it in register.js ,  ligne 358 .. by setting the "if" to "true" .. so i dont need any verification code to register .. i would see the lastest changes so am gonna clone the project again

**Comment by JackZheng10** [comment]
The latest changes were some other stuff I was working on. I tried bypassing it like you did and I was able to register successfully without a code and a random phone number. Have I clarified the issue for you then?

**Comment by hichemsmairia** [comment]
yes but for me it works smoothly after bypassing it .. anyways about handling user and washer and driver routes .. done ?

**Comment by JackZheng10** [comment]
The entire order process is done, from creation to completion. At the moment there is no differentiation between user types, so you can place an order and then accept the order on the same account. After that, you can see the order on your accepted dashboard.

When you mark the order as delivered to the washer, you'll have to register an account with the email w1@gmail.com (default email for washer) and you should be able to see the order at the path /washerAssigned.

From there, when done, you can accept the order again for final delivery. There's no GPS tracking right now for drivers, this may come later.

**Comment by hichemsmairia** [comment]
well done <3 <3 am gonna work on that

**Comment by JackZheng10** [comment]
Awesome. Any reason you took an interest in this project? And how did you find it?

**Comment by hichemsmairia** [comment]
all uber or like-uber projet are made with react native for android .. its hard to find s.th to inspire from

**Comment by hichemsmairia** [comment]
i still cant place orders

**Comment by JackZheng10** [comment]
What is the error you're getting?

**Comment by hichemsmairia** [comment]
enable to plae ur order .. in the last step after pricing

**Comment by JackZheng10** [comment]
Open your networking tab in Chrome and let me know the response you're getting.

**Comment by hichemsmairia** [comment]
![Screenshot from 2020-05-22 10-29-28](https://user-images.githubusercontent.com/44435049/82653583-5a37ab00-9c17-11ea-9c9d-bc29d43d3215.png)

**Comment by JackZheng10** [comment]
I meant the "Network" tab in your Chrome dev tools. Instructions are here: https://developers.google.com/web/tools/chrome-devtools/network

You should be able to see the network request it makes when the order gets placed. Let me know the response you're getting.

**Comment by hichemsmairia** [comment]
i know what means network tab .. i just showed u a screeshot to explain whats happening

**Comment by JackZheng10** [comment]
Ah okay. That's just an error I put there to catch any failure. The network response should be more descriptive.

**Comment by JackZheng10** [comment]
@hichemsmairia FYI, I have fixed the place order issue. It was throwing the error when counting an empty collection. If you have any other questions, feel free to open another issue!
